export enum ResourcesEnum {
  FOOD = "FOOD",
  WOOD = "WOOD",
  STONE = "STONE",
  GOLD = "GOLD",
  POPULATION = "POPULATION",
  SATISFACTION = "SATISFACTION",
  AMBER ="AMBER",
  TOOLS = "TOOLS",
  WEAPONS = "WEAPONS",
}
